
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ricca
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        panStorico.setVisible(true);
        panStorico.setEnabled(true);
        panDipendenti.setVisible(false);
        panDipendenti.setEnabled(false);
        panProgetti.setVisible(false);
        panProgetti.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panStorico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabStorico = new javax.swing.JTable();
        titoloStorico = new javax.swing.JLabel();
        cercaStorico = new javax.swing.JTextField();
        visitaDipendenti = new javax.swing.JButton();
        visitaProgetti = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        panDipendenti = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabDipendenti = new javax.swing.JTable();
        titoloDipendenti = new javax.swing.JLabel();
        cercaDipendenti = new javax.swing.JTextField();
        aggiungiDipendente = new javax.swing.JButton();
        eliminaDipendente = new javax.swing.JButton();
        modificaDipendente = new javax.swing.JButton();
        indietroDipendente = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        panProgetti = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabProgetti = new javax.swing.JTable();
        titoloProgetti = new javax.swing.JLabel();
        cercaProgetti = new javax.swing.JTextField();
        eliminaProgetti = new javax.swing.JButton();
        aggiungiProgetti = new javax.swing.JButton();
        modificaProgetti = new javax.swing.JButton();
        indietroProgetti = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabStorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Modifiche"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabStorico);

        titoloStorico.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        titoloStorico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titoloStorico.setText("Storico");

        visitaDipendenti.setText("Dipendenti");
        visitaDipendenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitaDipendentiActionPerformed(evt);
            }
        });

        visitaProgetti.setText("Progetti");
        visitaProgetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitaProgettiActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panStoricoLayout = new javax.swing.GroupLayout(panStorico);
        panStorico.setLayout(panStoricoLayout);
        panStoricoLayout.setHorizontalGroup(
            panStoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panStoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titoloStorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cercaStorico)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panStoricoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visitaProgetti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visitaDipendenti))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                .addContainerGap())
        );
        panStoricoLayout.setVerticalGroup(
            panStoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titoloStorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cercaStorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(panStoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitaDipendenti)
                    .addComponent(visitaProgetti)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabDipendenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Ruolo", "Progetti Attivi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabDipendenti);

        titoloDipendenti.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        titoloDipendenti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titoloDipendenti.setText("Dipendenti");

        aggiungiDipendente.setText("Aggiungi");
        aggiungiDipendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiDipendenteActionPerformed(evt);
            }
        });

        eliminaDipendente.setText("Elimina");

        modificaDipendente.setText("Modifica");

        indietroDipendente.setText("Indietro");
        indietroDipendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroDipendenteActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panDipendentiLayout = new javax.swing.GroupLayout(panDipendenti);
        panDipendenti.setLayout(panDipendentiLayout);
        panDipendentiLayout.setHorizontalGroup(
            panDipendentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDipendentiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDipendentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titoloDipendenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cercaDipendenti)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDipendentiLayout.createSequentialGroup()
                        .addComponent(indietroDipendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificaDipendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminaDipendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aggiungiDipendente))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addContainerGap())
        );
        panDipendentiLayout.setVerticalGroup(
            panDipendentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDipendentiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titoloDipendenti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cercaDipendenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panDipendentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aggiungiDipendente)
                    .addComponent(eliminaDipendente)
                    .addComponent(modificaDipendente)
                    .addComponent(indietroDipendente)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabProgetti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Stato", "Budget", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabProgetti);

        titoloProgetti.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        titoloProgetti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titoloProgetti.setText("Progetti");

        eliminaProgetti.setText("Elimina");

        aggiungiProgetti.setText("Aggiungi");

        modificaProgetti.setText("Modifica");

        indietroProgetti.setText("Indietro");
        indietroProgetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroProgettiActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panProgettiLayout = new javax.swing.GroupLayout(panProgetti);
        panProgetti.setLayout(panProgettiLayout);
        panProgettiLayout.setHorizontalGroup(
            panProgettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProgettiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProgettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titoloProgetti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cercaProgetti)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProgettiLayout.createSequentialGroup()
                        .addComponent(indietroProgetti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificaProgetti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminaProgetti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aggiungiProgetti)))
                .addContainerGap())
        );
        panProgettiLayout.setVerticalGroup(
            panProgettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProgettiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titoloProgetti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cercaProgetti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panProgettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aggiungiProgetti)
                    .addComponent(eliminaProgetti)
                    .addComponent(modificaProgetti)
                    .addComponent(indietroProgetti)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panStorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panDipendenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panProgetti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panDipendenti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panStorico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panProgetti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private Storico storico = new Storico("storico.csv");
    private Progetto[] vistaAttualeP = null;
    private Dipendente[] vistaAttualeD = null;
    int pos;
    
    
    
    private void visitaProgettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitaProgettiActionPerformed
        panStorico.setVisible(false);
        panStorico.setEnabled(false);
        panDipendenti.setVisible(false);
        panDipendenti.setEnabled(false);
        panProgetti.setVisible(true);
        panProgetti.setEnabled(true);
    }//GEN-LAST:event_visitaProgettiActionPerformed

    private void visitaDipendentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitaDipendentiActionPerformed
        panStorico.setVisible(false);
        panStorico.setEnabled(false);
        panDipendenti.setVisible(true);
        panDipendenti.setEnabled(true);
        panProgetti.setVisible(false);
        panProgetti.setEnabled(false);
    }//GEN-LAST:event_visitaDipendentiActionPerformed

    private void indietroDipendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroDipendenteActionPerformed
        panStorico.setVisible(true);
        panStorico.setEnabled(true);
        panDipendenti.setVisible(false);
        panDipendenti.setEnabled(false);
        panProgetti.setVisible(false);
        panProgetti.setEnabled(false);
    }//GEN-LAST:event_indietroDipendenteActionPerformed

    private void indietroProgettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroProgettiActionPerformed
        panStorico.setVisible(true);
        panStorico.setEnabled(true);
        panDipendenti.setVisible(false);
        panDipendenti.setEnabled(false);
        panProgetti.setVisible(false);
        panProgetti.setEnabled(false);
    }//GEN-LAST:event_indietroProgettiActionPerformed

    private void aggiungiDipendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiDipendenteActionPerformed
        storico.registraAggiunta("Dipendente");
    }//GEN-LAST:event_aggiungiDipendenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiungiDipendente;
    private javax.swing.JButton aggiungiProgetti;
    private javax.swing.JTextField cercaDipendenti;
    private javax.swing.JTextField cercaProgetti;
    private javax.swing.JTextField cercaStorico;
    private javax.swing.JButton eliminaDipendente;
    private javax.swing.JButton eliminaProgetti;
    private javax.swing.JButton indietroDipendente;
    private javax.swing.JButton indietroProgetti;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton modificaDipendente;
    private javax.swing.JButton modificaProgetti;
    private javax.swing.JPanel panDipendenti;
    private javax.swing.JPanel panProgetti;
    private javax.swing.JPanel panStorico;
    private javax.swing.JTable tabDipendenti;
    private javax.swing.JTable tabProgetti;
    private javax.swing.JTable tabStorico;
    private javax.swing.JLabel titoloDipendenti;
    private javax.swing.JLabel titoloProgetti;
    private javax.swing.JLabel titoloStorico;
    private javax.swing.JButton visitaDipendenti;
    private javax.swing.JButton visitaProgetti;
    // End of variables declaration//GEN-END:variables
}
